# Generated by Django 5.1 on 2026-07-04 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttentionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('focus_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_distracted', models.BooleanField(default=False)),
                ('head_pose_x', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('head_pose_y', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('eye_gaze_x', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('eye_gaze_y', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attention_logs', to='courses.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attention_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'attention_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('study_minutes', models.IntegerField(default=0)),
                ('focus_avg', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('quiz_score_avg', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('lessons_completed', models.IntegerField(default=0)),
                ('distraction_count', models.IntegerField(default=0)),
                ('engagement_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
