import api from './api';

const delay = (ms = 500) => new Promise(r => setTimeout(r, ms));

const videoService = {
  getVideoUrl: async (lessonId) => {
    await delay(200);
    return {
      data: {
        url: 'https://www.w3schools.com/html/mov_bbb.mp4',
        lessonId,
        duration: 596,
      },
    };
  },

  updateProgress: async (lessonId, currentTime, duration) => {
    await delay(100);
    return {
      data: {
        lessonId,
        progress: Math.round((currentTime / duration) * 100),
      },
    };
  },

  getTranscript: async (lessonId) => {
    await delay();
    return {
      data: {
        lessonId,
        transcript: 'This is a sample transcript for the video lesson. In a production environment, this would contain the full video transcript generated by speech-to-text services.',
      },
    };
  },
};

export default videoService;
